import React from 'react';
import { Inter } from 'next/font/google';

import Header from '@/components/Header/Header';
import Providers from '@/components/Providers/Providers';
import { SITE_NAME } from '@/constants/seo.constants';

import type { Metadata } from 'next';
import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: SITE_NAME,
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="ru">
      <body className={inter.className}>
        <Providers>
          <div className="w-full h-full">
            <Header />
            <main className="pt-[80px] h-full">{children}</main>
          </div>
        </Providers>
      </body>
    </html>
  );
}
